#!/usr/bin/env bash
# ping an IP address passed as an argument

# IP variable

IP="${1}"

# filename vRariable
fn=$(basename "{BASH_SOURCE[@]}")

if ! ["$IP"]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
