#!/usr/bin/env bash
# fixing issues arrised from using docker
# et Apache to run on the container and to return a page containing Hello ALX when querying the root of it.

sudo apt.get update -y
sudo apt.get install -y apache2
sudo /etc/init.d/apache2 start
sudo echo "Hello ALX" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
